### PR TITLE
Merge remote-tracking branch 'origin/cm-11.0' into jb-7.8

### PR DESCRIPTION
**Pull request by rtfpessoa**

### CODE REVIEW

**Comment by iptux** [comment]
kernel and *.ko modules

**Comment by rtfpessoa** [comment]
@iptux , what about the libs of the vendor repo. Do you think they have changes?

**Comment by iptux** [comment]
not recommended to update vendor repo.
the vendor repo for 3.4 kernel is a mix of  3.4 ROM(egl, firmware and camera stuff) and 3.0 ROM(all others)

**Comment by rtfpessoa** [comment]
@iptux how do you debug the ROM?
How do you find stuff about the init script for example?
I have some difficulties finding info about that.

Another thing, doesn't the new kernel have support for selinux too?

**Pull request merged**
